server:
  port: 9999
spring:
  application:
    name: mybatis-study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mybatis?zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
mybatis:
  type-aliases-package: com.g1335333249.entity
#  mapper-locations: classpath:com/g1335333249/mapper/*.xml
#  config-location: classpath:generatorConfig.xml
logging:
  level:
    com.g1335333249.mapper: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql